language: cpp

matrix:
  include:  

    ## Linux(Trusty) - GCC-4.8 - Release
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - kubuntu-backports
          packages:
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - mesa-common-dev
      env:
        - MATRIX_EVAL="BUILD_TYPE=Release"

    ## Linux(Trusty) - CLANG 5 - Release
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - kubuntu-backports
            - llvm-toolchain-trusty-5.0            
          packages:
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - mesa-common-dev
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && BUILT_TYPE=Release"


before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - cmake --build . -- -j10
  - ctest -j10 -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false