language: bash

templates:
  windows: &windows
    os: windows
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH

  linux: &linux
    addons:
      apt:
        sources:
          - kubuntu-backports
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0            
        packages:
          - cmake
          - libxrandr-dev
          - libxinerama-dev
          - libxcursor-dev
          - libxi-dev
          - libglu1-mesa-dev
          - freeglut3-dev
          - mesa-common-dev
          - libboost-dev
          - libboost-filesystem-dev

matrix:
  include:  

    ###########################################################################
    # GCC on Linux 
    ###########################################################################
    - env: GENERATOR="Unix Makefiles" CXX=g++-5 && CC=gcc-5 
      <<: *linux
      
    ###########################################################################
    # GCC on Linux 
    ###########################################################################
    - env: GENERATOR="Unix Makefiles" CXX=clang++-5.0 CC=clang-5.0
      <<: *linux      

    ###########################################################################
    # MSVC on Windows
    ###########################################################################
    - env: GENERATOR="Visual Studio 15 2017 Win64"
      <<: *windows

    - env: GENERATOR="Visual Studio 15 2017"
      <<: *windows

    ###########################################################################
    # Clang on OSX
    ###########################################################################
    - env: GENERATOR="Unix Makefiles" CXX=clang++ CC=clang
      os: osx
      osx_image: xcode10

    - env: GENERATOR="Unix Makefiles" CXX=clang++ CC=clang
      os: osx
      osx_image: xcode9.4

    - env: GENERATOR="Unix Makefiles" CXX=clang++ CC=clang
      os: osx
      osx_image: xcode8.3

script:
  ###########################################################################
  # Common flags
  ###########################################################################
  - export CMAKE_FLAGS="-DGLFW_BUILD_EXAMPLES=0 -DGLFW_BUILD_TESTS=0"

  ###########################################################################
  # Debug
  ###########################################################################
  - mkdir -p build/Debug
  - cd build/Debug
  - cmake -G "${GENERATOR}" ${CMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug ../../
  - cmake --build . --config Debug
  - ctest --output-on-failure
  - cd ../..

  ###########################################################################
  # Release
  ###########################################################################
  - mkdir -p build/Release
  - cd build/Release
  - cmake -G "${GENERATOR}" ${CMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Release ../../
  - cmake --build . --config Release
  - ctest --output-on-failure
  - cd ../..

notifications:
  email: false