language: bash

templates:
  windows: &windows
    os: windows
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH
    install:
      - choco install directx

  linux: &linux
    addons:
      apt:
        sources:
          - kubuntu-backports
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
          - llvm-toolchain-trusty-6.0
          - llvm-toolchain-trusty-7
        packages:
          - cmake
          - libxrandr-dev
          - libxinerama-dev
          - libxcursor-dev
          - libxi-dev
          - libglu1-mesa-dev
          - freeglut3-dev
          - mesa-common-dev
          - libboost-dev
          - libboost-filesystem-dev
          - g++-5
          - gcc-5 
          - g++-6
          - gcc-6
          - g++-7
          - gcc-7 
          - g++-8
          - gcc-8 
          - clang-4.0
          - clang-5.0 
          - clang-6.0
          - clang-7 

matrix:
  include:  

    ###########################################################################
    # GCC on Linux 
    ###########################################################################
    - env: GENERATOR="Unix Makefiles" CXX=g++-5 CC=gcc-5
      <<: *linux
      
    - env: GENERATOR="Unix Makefiles" CXX=g++-6 CC=gcc-6
      <<: *linux
      
    - env: GENERATOR="Unix Makefiles" CXX=g++-7 CC=gcc-7
      <<: *linux
      
    - env: GENERATOR="Unix Makefiles" CXX=g++-8 CC=gcc-8
      <<: *linux
      
    ###########################################################################
    # Clang on Linux 
    ###########################################################################
    - env: GENERATOR="Unix Makefiles" CXX=clang++-4.0 CC=clang-4.0
      <<: *linux

    - env: GENERATOR="Unix Makefiles" CXX=clang++-5.0 CC=clang-5.0
      <<: *linux

    - env: GENERATOR="Unix Makefiles" CXX=clang++-6.0 CC=clang-6.0
      <<: *linux
          
    - env: GENERATOR="Unix Makefiles" CXX=clang++-7 CC=clang-7
      <<: *linux

    ###########################################################################
    # MSVC on Windows
    ###########################################################################
    - env: GENERATOR="Visual Studio 15 2017 Win64"
      <<: *windows

    - env: GENERATOR="Visual Studio 15 2017"
      <<: *windows

    ###########################################################################
    # Clang on OSX
    ###########################################################################
    - env: GENERATOR="Unix Makefiles" CXX=clang++ CC=clang
      os: osx
      osx_image: xcode10

    - env: GENERATOR="Unix Makefiles" CXX=clang++ CC=clang
      os: osx
      osx_image: xcode9.4

    - env: GENERATOR="Unix Makefiles" CXX=clang++ CC=clang
      os: osx
      osx_image: xcode8.3

    - env: GENERATOR="Unix Makefiles" CXX=clang++ CC=clang
      os: osx
      osx_image: xcode7.3

    - env: GENERATOR="Unix Makefiles" CXX=clang++ CC=clang
      os: osx
      osx_image: xcode6.4

script:
  ###########################################################################
  # Debug
  ###########################################################################
  - mkdir -p build/Debug
  - cd build/Debug
  - cmake -G "${GENERATOR}" ${CMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug ../../
  - cmake --build . --config Debug
  - ctest --output-on-failure
  - cd ../..

  ###########################################################################
  # Release
  ###########################################################################
  - mkdir -p build/Release
  - cd build/Release
  - cmake -G "${GENERATOR}" ${CMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Release ../../
  - cmake --build . --config Release
  - ctest --output-on-failure
  - cd ../..

notifications:
  email: false