language: cpp

matrix:
  include:  
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - kubuntu-backports
          packages:
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - mesa-common-dev
      env:
        - MATRIX_EVAL="BUILD_TYPE=Release"


before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - cmake --build . -- -j10
  - ctest -j10 -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false