language: cpp

compiler:
  - gcc
  - clang

# necessary for GLFW
addons:
    apt:
        sources:
            - kubuntu-backports
            - llvm-toolchain-trusty-5.0
        packages:
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - mesa-common-dev
            - clang-5.0

env:
  global:
    - CC=clang-5.0
    - CXX=clang++-5.0    
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_script:
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - cmake --build . -- -j10
  - ctest -j10 -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false